workspace = { members = [ "src/pyrev_ast", "src/pyrev_ast_derive" ] }

[package]
name = "pyrev"
authors = ["hacbit <hacbit@foxmail.com>"]
version = "1.0.2"
edition = "2021"

[features]
clippy = []

[dependencies]
atty = "0.2.14"
colored = "2.0.4"
lazy_format = "2.0.0"
lazy_static = "1.4.0"
regex = "1.10.2"

[dependencies.clap]
version = "4.5.1"
features = ["derive", "cargo"]

[dependencies.pyrev_ast]
path = "src/pyrev_ast"

[profile.dev]
# Uncomment the following lines to allow clippy to break your build.
# rustflags = ["-D", "warnings"]